### ISSUE TITLE
How to download tuxguitar source code and use it?

### ISSUE THREAD

**Issue by domas94** [yth1130/tuxguitar-korean#1]
Hi,
could you please tell me how is it possible to download original tuxguitar source code?

**Comment by yth1130** [comment]
Maybe this site is what you want : https://sourceforge.net/p/tuxguitar/code/
But I don't know how to build it..
Why you want tuxguitar source code?

**Comment by domas94** [comment]
Thank you for your answer. I know about that site but I also don't know how to build that. That repository has android and pc content. I want the source code so I could turn on lights as music plays. Every note would have its own LED.
