### ISSUE TITLE
Redistribute tuxguitar-korean with TuxGuitar under LGPL-2.1+?

### ISSUE THREAD

**Issue by helge17** [yth1130/tuxguitar-korean#2]
First of all, thank you very much for your translation!
I added it to my TuxGuitar fork https://github.com/helge17/tuxguitar
Is it ok to share your file under the LGPL-2.1+ license, which TuxGuitar also uses for most of its source code?

**Comment by yth1130** [comment]
Hi @helge17 !
Sure, you can use and share this file. Thank you for using.
By the way, How is that fork different from the original?

**Comment by helge17** [comment]
OK, thanks!
For the user, there is currently not much difference from the last version on Sourceforge. But it seems that development has stalled there, so we are trying to give TuxGuitar a new future.

**Comment by yth1130** [comment]
Oh, nice! I'm looking forward to your project 👍
